version: '3.9'

services:
  mariadb:
    build: requirements/mariadb/.
    container_name: mariadb
    env_file: .env
    volumes:
      - ./database:/var/lib/mysql
    networks:
      - inception

  wordpress:
    build: requirements/wordpress/.
    container_name: wordpress
    depends_on:
      - mariadb
    env_file: .env
    volumes:
      - ./web:/var/www/html
    networks:
      - inception

  nginx:
    build: requirements/nginx/.
    container_name: nginx
    depends_on:
      - wordpress
    env_file: .env
    ports:
      - "443:443"
    volumes:
      - ./web:/var/www/html
    networks:
      - inception

networks:
  inception: